---
- name: Look for existing install in {{ nancy_install_dir }}
  become: '{{ nancy_privilege_escalate }}'
  become_user: root
  changed_when: false
  ansible.builtin.stat:
    path: '{{ nancy_install_dir }}'
  register: nancy_binary
- name: Downloading and installing nancy
  when: not nancy_binary.stat.exists
  block:
    - name: Download nancy {{ nancy_ver }} from {{ nancy_url }}
      become: '{{ nancy_privilege_escalate }}'
      become_user: root
      ansible.builtin.get_url:
        url: '{{ nancy_url }}'
        checksum: '{{ nancy_checksum }}'
        dest: '{{ nancy_tmp_archive }}'
        mode: '644'
    - name: Make versioned directory to hold nancy {{ nancy_ver }} at {{ nancy_install_dir }}
      become: '{{ nancy_privilege_escalate }}'
      become_user: root
      ansible.builtin.file:
        path: '{{ nancy_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive nancy {{ nancy_ver }} from {{ nancy_tmp_archive }}
      become: '{{ nancy_privilege_escalate }}'
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ nancy_tmp_archive }}'
        dest: '{{ nancy_install_dir }}'
        creates: '{{ nancy_install_exe }}'
  always:
    - name: Rm {{ nancy_tmp_archive }}
      become: '{{ nancy_privilege_escalate }}'
      become_user: root
      ansible.builtin.file:
        path: '{{ nancy_tmp_archive }}'
        state: absent
- name: Link nancy and nancy-{{ nancy_ver }}
  become: '{{ nancy_privilege_escalate }}'
  become_user: root
  with_items:
    - '{{ nancy_link }}'
    - '{{ nancy_ver_link }}'
  ansible.builtin.file:
    src: '{{ nancy_install_exe }}'
    dest: '{{ item }}'
    state: link
